  api:
    restart: always
    build: ./api
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - api
      - front
    links:
      - api:api
      - front:front

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/

  front:
    restart: always
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/front

  sample-server:
    restart: always
    build: ./sample-server
    ports:
      - "9999:9999"
    volumes:
      - /usr/src/sample-server